apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-app-deployment
  labels:
    app: cluster-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cluster-app
  template:
    metadata:
      labels:
        app: cluster-app
    spec:
      containers:
      - name: cluster-app
        image: aidanranney/cluster-app:0.1.3
        ports:
        - containerPort: 4000
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: cluster-app-secret
              key: key_base
        - name: PHX_HOST
          valueFrom:
            configMapKeyRef:
              name: cluster-app-config-map
              key: phx_host
        - name: DNS_CLUSTER_QUERY
          valueFrom:
            configMapKeyRef:
              name: cluster-app-config-map
              key: headless_service_dns
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      imagePullSecrets:
      - name: myregistrykey
