apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-app-deployment
  labels:
    app: cluster-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-app
  template:
    metadata:
      labels:
        app: cluster-app
    spec:
      containers:
      - name: myapp
        image: aidanranney/cluster-app:0.0.4
        ports:
        - containerPort: 4000
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: cluster-app-secret
              key: key_base
