apiVersion: v1
kind: Service
metadata:
  name: cluster-app-service
spec:
  selector:
    app: cluster-app
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-app-headless-service
spec:
  selector:
    app: cluster-app
  type: ClusterIP
  clusterIP: "None"
